### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by pizza2code** [alexgorbatchev/gulp-typescript-webpack-react-hotreload#6]
The project fails to build with the following Typescript compile error.  I made no changes after cloning.
```
[14:07:34] Requiring external module ts-node/register
TSError: ⨯ Unable to compile TypeScript
src/routes/blog/containers/BlogContainer-spec.tsx (9,7): Property 'authors' is missing in type 'IntrinsicAttributes & IntrinsicClassAttributes<BlogContainer> & IPostsProps & { children?: ReactE...'. (2324)
src/routes/blog/containers/BlogContainer-spec.tsx (9,7): Property 'displayPosts' is missing in type 'IntrinsicAttributes & IntrinsicClassAttributes<BlogContainer> & IPostsProps & { children?: ReactE...'. (2324)
src/routes/blog/containers/BlogContainer-spec.tsx (9,7): Property 'isFetching' is missing in type 'IntrinsicAttributes & IntrinsicClassAttributes<BlogContainer> & IPostsProps & { children?: ReactE...'. (2324)
src/routes/blog/containers/BlogContainer-spec.tsx (9,7): Property 'posts' is missing in type 'IntrinsicAttributes & IntrinsicClassAttributes<BlogContainer> & IPostsProps & { children?: ReactE...'. (2324)
    at getOutput (/bfp/common/vob/web/pane/gulp-typescript-webpack-react-hotreload/node_modules/ts-node/src/ts-node.ts:210:13)
    at Object.loader (/bfp/common/vob/web/pane/gulp-typescript-webpack-react-hotreload/node_modules/ts-node/src/ts-node.ts:225:23)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Liftoff.handleArguments (/usr/people/guinncd1/node.js/node-v4.2.2-linux-x64/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/people/guinncd1/node.js/node-v4.2.2-linux-x64/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/usr/people/guinncd1/node.js/node-v4.2.2-linux-x64/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/usr/people/guinncd1/node.js/node-v4.2.2-linux-x64/lib/node_modules/gulp/node_modules/liftoff/index.js:185:9)
```

**Comment by cubabit** [comment]
I fixed this with:

```
diff --git a/src/routes/blog/containers/BlogContainer-spec.tsx b/src/routes/blog/containers/BlogContainer-spec.tsx
index 0158f14..4815a06 100644
--- a/src/routes/blog/containers/BlogContainer-spec.tsx
+++ b/src/routes/blog/containers/BlogContainer-spec.tsx
@@ -6,7 +6,7 @@ import BlogContainer from './BlogContainer';
 describe('BlogContainer', function() {
   it('works', function() {
     const instance = TestUtils.renderIntoDocument(
-      <BlogContainer />
+      <BlogContainer authors={{}} displayPosts={[]} isFetching={false} posts={{}} />
     );

     expect(instance).to.be.ok;
```
